# Generated by Django 5.2.14 on 2026-05-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='display_name',
            field=models.CharField(blank=True, help_text='Nombre tal como figura en el Excel', max_length=160),
        ),
    ]
